// Referral home screen — wires the surface to /referral/* endpoints.
// Spec: docs/mobile/specs/08-referral.ru.md.
//
// - Hero displays the customer's referral code (lazily generated by the
//   server on first read) with copy + share affordances.
// - Stats / monthly cap reflect the live summary from GET /referral.
// - Invite section accepts an email or E.164 phone, autodetects the channel,
//   and delegates to useSendInvite (idempotent). The "Share link" CTA mints
//   a link-channel invite and hands the URL to the system Share sheet.
// - Friends list is hydrated from GET /referral/friends (cursor pagination)
//   and grouped by stage. Avatars use the Bolt-brief #12 grey treatment.

import * as Clipboard from 'expo-clipboard';
import * as Haptics from 'expo-haptics';
import { useRouter } from 'expo-router';
import {
  ArrowLeft,
  Copy,
  Share2,
  Users,
  ChevronRight,
  RefreshCw,
} from 'lucide-react-native';
import React, { useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Modal,
  RefreshControl,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

import { toast } from '@/components/ui/Toast';
import { useTheme } from '@/context/ThemeContext';
import { useGenerateReferralCode } from '@/hooks/useGenerateReferralCode';
import { useReferralFriends } from '@/hooks/useReferralFriends';
import { useReferralSummary } from '@/hooks/useReferralSummary';
import { useSendInvite } from '@/hooks/useSendInvite';
import type {
  ReferralFriend,
  ReferralStage,
  SendInviteRequest,
} from '@/types/referral';
import { ApiError, mapErrorCode } from '@/utils/errors';
import { formatMoney } from '@/utils/format';
import { isValidE164, isValidEmail } from '@/utils/validators';

const AVATAR_BG = '#E2E8F0';
const AVATAR_FG = '#64748B';

const STAGE_LABELS: Record<ReferralStage, string> = {
  invited: 'Invited',
  joined: 'Joined',
  topped_up: 'Topped up',
  reward_posted: 'Reward posted',
};

const STAGE_COLORS: Record<ReferralStage, { bg: string; text: string }> = {
  invited: { bg: '#f1f5f9', text: '#475569' },
  joined: { bg: '#dbeafe', text: '#1d4ed8' },
  topped_up: { bg: '#fef3c7', text: '#92400e' },
  reward_posted: { bg: '#dcfce7', text: '#15803d' },
};

const STAGE_COLORS_DARK: Record<ReferralStage, { bg: string; text: string }> = {
  invited: { bg: '#334155', text: '#94A3B8' },
  joined: { bg: '#1E3A5F', text: '#3B82F6' },
  topped_up: { bg: '#422006', text: '#FBBF24' },
  reward_posted: { bg: '#064E3B', text: '#34D399' },
};

const STAGE_ORDER: ReferralStage[] = [
  'reward_posted',
  'topped_up',
  'joined',
  'invited',
];

function avatarInitial(friend: ReferralFriend): string {
  const source = friend.inviteeName ?? friend.displayName ?? friend.contactMasked;
  if (!source || source.length === 0) return '?';
  const ch = source.replace(/\s+/g, '').charAt(0);
  return ch.toUpperCase();
}

function friendDisplayName(friend: ReferralFriend): string {
  if (friend.inviteeName) return friend.inviteeName;
  if (friend.displayName) return friend.displayName;
  if (friend.contactMasked) return friend.contactMasked;
  return 'Pending invite';
}

export default function ReferralScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { colors, isDark } = useTheme();

  const summaryQuery = useReferralSummary();
  const friendsQuery = useReferralFriends();
  const generateCode = useGenerateReferralCode();

  const [inviteOpen, setInviteOpen] = useState(false);

  const stageColors = isDark ? STAGE_COLORS_DARK : STAGE_COLORS;

  const summary = summaryQuery.data;
  const friends = friendsQuery.data;
  const code = summary?.code?.code ?? null;
  const deepLink = summary?.code?.deepLink ?? null;
  const currency = summary?.totals.rewardsEarnedAmount.currency ?? 'GBP';

  const programErrorCode =
    summaryQuery.error instanceof ApiError ? summaryQuery.error.code : null;
  const isDisabled = programErrorCode === 'REFERRAL_DISABLED';

  // Pre-formatted programme copy from the server-side config so the UI
  // never hard-codes "£5". Falls back to a neutral string while the
  // summary is loading.
  const heroTitle = useMemo(() => {
    if (!summary) return 'Invite friends';
    const inviter =
      summary.config.inviterJoinBonus.amountMinor +
      summary.config.inviterTopupBonus.amountMinor;
    const invitee = summary.config.inviteeWelcomeBonus.amountMinor;
    return `Give ${formatMoney(invitee, currency)}, get ${formatMoney(
      inviter,
      currency,
    )}`;
  }, [summary, currency]);

  const heroSub = useMemo(() => {
    if (!summary) return 'Invite friends and earn together when they top up.';
    const min = formatMoney(summary.config.minTopup.amountMinor, currency);
    return `Invite friends. When they sign up and top up ${min} or more, you both earn rewards.`;
  }, [summary, currency]);

  const onRefresh = React.useCallback(() => {
    void summaryQuery.refetch();
    void friendsQuery.refresh();
  }, [summaryQuery, friendsQuery]);

  const copyCode = async () => {
    if (!code) return;
    try {
      await Clipboard.setStringAsync(code);
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      toast.show({ message: `Code ${code} copied`, variant: 'success' });
    } catch {
      // best-effort
    }
  };

  const shareInvite = async () => {
    if (!code || !deepLink) return;
    try {
      const message = `Join with my code ${code} — ${deepLink}`;
      await Share.share({ message, url: deepLink });
    } catch {
      // user cancelled — no-op
    }
  };

  const onRotateCode = () => {
    Alert.alert(
      'Generate a new code?',
      `Your current code ${code ?? ''} will be replaced. Friends who already have the old code can still use it.`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Generate',
          style: 'destructive',
          onPress: async () => {
            try {
              const result = await generateCode.mutate();
              await Haptics.notificationAsync(
                Haptics.NotificationFeedbackType.Success,
              );
              await summaryQuery.refetch();
              toast.show({
                message: `New code: ${result.code}`,
                variant: 'success',
              });
            } catch (e) {
              const message =
                e instanceof ApiError
                  ? mapErrorCode(e.code) ?? e.message
                  : 'Could not generate a new code right now.';
              Alert.alert('Error', message);
            }
          },
        },
      ],
    );
  };

  // --- Render ---------------------------------------------------------------

  if (isDisabled) {
    return (
      <SafeAreaView
        edges={['left', 'right']}
        style={[styles.safe, { backgroundColor: colors.background }]}
      >
        <Header insets={insets} colors={colors} onBack={() => router.back()} />
        <View style={styles.placeholder}>
          <Users size={48} color={colors.textTertiary} />
          <Text style={[styles.placeholderTitle, { color: colors.text }]}>
            Referrals are unavailable
          </Text>
          <Text style={[styles.placeholderSub, { color: colors.textSecondary }]}>
            The referral programme isn't available at the moment. Please check back later.
          </Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView
      edges={['left', 'right']}
      style={[styles.safe, { backgroundColor: colors.background }]}
    >
      <Header
        insets={insets}
        colors={colors}
        onBack={() => router.back()}
        rightAction={code ? onRotateCode : undefined}
        rightLoading={generateCode.loading}
      />

      <ScrollView
        contentContainerStyle={[
          styles.scroll,
          { paddingBottom: insets.bottom + 24 },
        ]}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={summaryQuery.loading || friendsQuery.refreshing}
            onRefresh={onRefresh}
            tintColor={colors.primary}
          />
        }
      >
        {/* Hero */}
        <View style={styles.hero}>
          <View
            style={[
              styles.heroIconBg,
              { backgroundColor: isDark ? colors.surfaceAlt : '#eff6ff' },
            ]}
          >
            <Users size={40} color={colors.primary} />
          </View>
          <Text style={[styles.heroTitle, { color: colors.text }]}>
            {heroTitle}
          </Text>
          <Text style={[styles.heroSub, { color: colors.textSecondary }]}>
            {heroSub}
          </Text>
        </View>

        {/* Code card */}
        <View
          style={[
            styles.codeCard,
            {
              backgroundColor: colors.surface,
              shadowColor: colors.shadowColor,
            },
          ]}
        >
          <Text style={[styles.codeLabel, { color: colors.textTertiary }]}>
            Your referral code
          </Text>
          <TouchableOpacity
            style={[
              styles.codeRow,
              {
                backgroundColor: colors.background,
                borderColor: colors.border,
              },
            ]}
            onPress={copyCode}
            disabled={!code}
            accessibilityRole="button"
            accessibilityLabel="Copy referral code"
          >
            <Text style={[styles.codeText, { color: colors.text }]}>
              {code ?? '••••••••'}
            </Text>
            <Copy size={18} color={colors.primary} />
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.shareBtn, { backgroundColor: colors.primary }]}
            onPress={shareInvite}
            disabled={!code}
            accessibilityRole="button"
            accessibilityLabel="Share referral link"
          >
            <Share2 size={16} color="#fff" />
            <Text style={styles.shareBtnText}>Share invite</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[
              styles.inviteBtn,
              { borderColor: colors.primary },
            ]}
            onPress={() => setInviteOpen(true)}
            disabled={!code}
            accessibilityRole="button"
            accessibilityLabel="Send invite by email or SMS"
          >
            <Text style={[styles.inviteBtnText, { color: colors.primary }]}>
              Send invite by email or SMS
            </Text>
          </TouchableOpacity>
        </View>

        {/* Stats */}
        {summary && (
          <View
            style={[
              styles.statsRow,
              {
                backgroundColor: colors.surface,
                shadowColor: colors.shadowColor,
              },
            ]}
          >
            <Stat
              label="Invited"
              value={String(summary.totals.invitesSent)}
              colors={colors}
            />
            <Stat
              label="Joined"
              value={String(summary.totals.friendsJoined)}
              colors={colors}
            />
            <Stat
              label="Earned"
              value={formatMoney(
                summary.totals.rewardsEarnedAmount.amountMinor,
                summary.totals.rewardsEarnedAmount.currency,
              )}
              colors={colors}
            />
          </View>
        )}

        {/* Monthly cap */}
        {summary && summary.monthlyCap.limit > 0 && (
          <View
            style={[
              styles.capRow,
              {
                backgroundColor: colors.surface,
                shadowColor: colors.shadowColor,
              },
            ]}
          >
            <Text style={[styles.capText, { color: colors.textSecondary }]}>
              Monthly limit: {summary.monthlyCap.rewarded} /{' '}
              {summary.monthlyCap.limit} referrals rewarded
            </Text>
            <View style={[styles.capTrack, { backgroundColor: colors.border }]}>
              <View
                style={[
                  styles.capFill,
                  {
                    backgroundColor:
                      summary.monthlyCap.remaining === 0
                        ? colors.red
                        : colors.primary,
                    width: `${Math.min(
                      100,
                      (summary.monthlyCap.rewarded /
                        summary.monthlyCap.limit) *
                        100,
                    )}%`,
                  },
                ]}
              />
            </View>
            {summary.monthlyCap.remaining === 0 && (
              <Text style={[styles.capWarn, { color: colors.red }]}>
                Cap reached for {summary.monthlyCap.yearMonth}.
              </Text>
            )}
          </View>
        )}

        {/* Programme terms */}
        {summary && (
          <View
            style={[
              styles.termsCard,
              {
                backgroundColor: colors.surface,
                shadowColor: colors.shadowColor,
              },
            ]}
          >
            <Text style={[styles.sectionTitle, { color: colors.text }]}>
              How it works
            </Text>
            <Step
              num="1"
              title="Share your code"
              desc="Send your code to friends via email, SMS or share-link."
              colors={colors}
            />
            <Step
              num="2"
              title="Friend signs up"
              desc={`They register a new account using your code and get a ${formatMoney(
                summary.config.inviteeWelcomeBonus.amountMinor,
                currency,
              )} welcome bonus.`}
              colors={colors}
            />
            <Step
              num="3"
              title="Friend tops up"
              desc={`They top up ${formatMoney(
                summary.config.minTopup.amountMinor,
                currency,
              )} or more.`}
              colors={colors}
            />
            <Step
              num="4"
              title="You earn rewards"
              desc={`You receive ${formatMoney(
                summary.config.inviterJoinBonus.amountMinor +
                  summary.config.inviterTopupBonus.amountMinor,
                currency,
              )} in your wallet.`}
              colors={colors}
            />
          </View>
        )}

        {/* Friends list, grouped by stage */}
        <FriendsSection
          friends={friends}
          loading={friendsQuery.loading}
          onPressFriend={(id) =>
            router.push({
              pathname: '/referral/friend/[id]',
              params: { id },
            })
          }
          stageColors={stageColors}
          colors={colors}
        />
      </ScrollView>

      <InviteModal
        visible={inviteOpen}
        onClose={() => setInviteOpen(false)}
        onAfterSubmit={() => {
          void summaryQuery.refetch();
          void friendsQuery.refresh();
        }}
        colors={colors}
        isDark={isDark}
      />
    </SafeAreaView>
  );
}

// --- Header ---------------------------------------------------------------

interface HeaderProps {
  insets: { top: number };
  colors: ReturnType<typeof useTheme>['colors'];
  onBack: () => void;
  rightAction?: () => void;
  rightLoading?: boolean;
}

function Header({ insets, colors, onBack, rightAction, rightLoading }: HeaderProps) {
  return (
    <View
      style={[
        styles.header,
        {
          backgroundColor: colors.surface,
          borderBottomColor: colors.border,
          paddingTop: insets.top + 14,
        },
      ]}
    >
      <TouchableOpacity onPress={onBack} style={styles.backBtn}>
        <ArrowLeft size={22} color={colors.text} />
      </TouchableOpacity>
      <Text style={[styles.title, { color: colors.text }]}>Invite Friends</Text>
      {rightAction ? (
        <TouchableOpacity
          onPress={rightAction}
          style={styles.backBtn}
          disabled={rightLoading}
          accessibilityRole="button"
          accessibilityLabel="Generate new referral code"
        >
          {rightLoading ? (
            <ActivityIndicator size="small" color={colors.text} />
          ) : (
            <RefreshCw size={18} color={colors.text} />
          )}
        </TouchableOpacity>
      ) : (
        <View style={{ width: 36 }} />
      )}
    </View>
  );
}

// --- Stat -----------------------------------------------------------------

function Stat({
  label,
  value,
  colors,
}: {
  label: string;
  value: string;
  colors: ReturnType<typeof useTheme>['colors'];
}) {
  return (
    <View style={styles.statItem}>
      <Text style={[styles.statValue, { color: colors.text }]}>{value}</Text>
      <Text style={[styles.statLabel, { color: colors.textTertiary }]}>
        {label}
      </Text>
    </View>
  );
}

// --- Step (programme terms) ----------------------------------------------

function Step({
  num,
  title,
  desc,
  colors,
}: {
  num: string;
  title: string;
  desc: string;
  colors: ReturnType<typeof useTheme>['colors'];
}) {
  return (
    <View style={styles.step}>
      <View style={[styles.stepNum, { backgroundColor: colors.primary }]}>
        <Text style={styles.stepNumText}>{num}</Text>
      </View>
      <View style={styles.stepContent}>
        <Text style={[styles.stepTitle, { color: colors.text }]}>{title}</Text>
        <Text style={[styles.stepDesc, { color: colors.textSecondary }]}>
          {desc}
        </Text>
      </View>
    </View>
  );
}

// --- Friends section ------------------------------------------------------

interface FriendsSectionProps {
  friends: ReferralFriend[];
  loading: boolean;
  onPressFriend: (id: string) => void;
  stageColors: Record<ReferralStage, { bg: string; text: string }>;
  colors: ReturnType<typeof useTheme>['colors'];
}

function FriendsSection({
  friends,
  loading,
  onPressFriend,
  stageColors,
  colors,
}: FriendsSectionProps) {
  if (loading && friends.length === 0) {
    return (
      <View style={styles.section}>
        <ActivityIndicator size="small" color={colors.primary} />
      </View>
    );
  }

  if (friends.length === 0) {
    return (
      <View
        style={[
          styles.emptyCard,
          {
            backgroundColor: colors.surface,
            shadowColor: colors.shadowColor,
          },
        ]}
      >
        <Users size={32} color={colors.textTertiary} />
        <Text style={[styles.emptyTitle, { color: colors.text }]}>
          No friends yet
        </Text>
        <Text style={[styles.emptySub, { color: colors.textSecondary }]}>
          Share your code to invite your first friend.
        </Text>
      </View>
    );
  }

  // Group by stage in a fixed display order.
  const groups: Record<ReferralStage, ReferralFriend[]> = {
    reward_posted: [],
    topped_up: [],
    joined: [],
    invited: [],
  };
  for (const f of friends) groups[f.stage].push(f);

  return (
    <View style={styles.section}>
      <Text style={[styles.sectionTitle, { color: colors.text }]}>
        Your friends
      </Text>
      {STAGE_ORDER.map((stage) => {
        const list = groups[stage];
        if (list.length === 0) return null;
        return (
          <View key={stage} style={{ marginBottom: 12 }}>
            <Text
              style={[styles.groupHeader, { color: colors.textTertiary }]}
            >
              {STAGE_LABELS[stage]} ({list.length})
            </Text>
            {list.map((friend) => (
              <FriendRow
                key={friend.id}
                friend={friend}
                stageColors={stageColors}
                colors={colors}
                onPress={() => onPressFriend(friend.id)}
              />
            ))}
          </View>
        );
      })}
    </View>
  );
}

function FriendRow({
  friend,
  stageColors,
  colors,
  onPress,
}: {
  friend: ReferralFriend;
  stageColors: Record<ReferralStage, { bg: string; text: string }>;
  colors: ReturnType<typeof useTheme>['colors'];
  onPress: () => void;
}) {
  const chip = stageColors[friend.stage];
  const earned = friend.inviterEarned.amountMinor;
  return (
    <TouchableOpacity
      style={[styles.friendRow, { borderBottomColor: colors.borderLight }]}
      onPress={onPress}
      accessibilityRole="button"
    >
      <View style={[styles.friendAvatar, { backgroundColor: AVATAR_BG }]}>
        <Text style={[styles.friendAvatarText, { color: AVATAR_FG }]}>
          {avatarInitial(friend)}
        </Text>
      </View>
      <View style={styles.friendInfo}>
        <Text style={[styles.friendName, { color: colors.text }]}>
          {friendDisplayName(friend)}
        </Text>
        {earned > 0 && (
          <Text style={[styles.friendReward, { color: colors.green }]}>
            +
            {formatMoney(earned, friend.inviterEarned.currency)} earned
          </Text>
        )}
      </View>
      <View style={[styles.stageChip, { backgroundColor: chip.bg }]}>
        <Text style={[styles.stageChipText, { color: chip.text }]}>
          {STAGE_LABELS[friend.stage]}
        </Text>
      </View>
      <ChevronRight size={16} color={colors.textTertiary} />
    </TouchableOpacity>
  );
}

// --- Invite modal ---------------------------------------------------------

interface InviteModalProps {
  visible: boolean;
  onClose: () => void;
  onAfterSubmit: () => void;
  colors: ReturnType<typeof useTheme>['colors'];
  isDark: boolean;
}

function InviteModal({
  visible,
  onClose,
  onAfterSubmit,
  colors,
  isDark,
}: InviteModalProps) {
  const insets = useSafeAreaInsets();
  const sendInvite = useSendInvite();
  const [contact, setContact] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [inlineError, setInlineError] = useState<string | null>(null);
  // Track whether the form has been submitted at least once — fields are
  // cleared on close via onClose.
  const submittedRef = useRef(false);

  const reset = () => {
    setContact('');
    setDisplayName('');
    setInlineError(null);
    sendInvite.reset();
    submittedRef.current = false;
  };

  const handleClose = () => {
    reset();
    onClose();
  };

  const detectChannel = (
    raw: string,
  ): SendInviteRequest | { error: string } => {
    const trimmed = raw.trim();
    if (trimmed.length === 0) {
      return { error: 'Please enter an email or phone number.' };
    }
    if (isValidEmail(trimmed)) {
      const payload: SendInviteRequest = {
        channel: 'email',
        email: trimmed,
      };
      if (displayName.trim().length > 0) {
        (payload as { displayName?: string }).displayName = displayName.trim();
      }
      return payload;
    }
    if (isValidE164(trimmed)) {
      const payload: SendInviteRequest = {
        channel: 'sms',
        phoneE164: trimmed,
      };
      if (displayName.trim().length > 0) {
        (payload as { displayName?: string }).displayName = displayName.trim();
      }
      return payload;
    }
    return {
      error:
        'Enter a valid email or phone number in international format (e.g. +447911123456).',
    };
  };

  const onSubmit = async () => {
    setInlineError(null);
    const built = detectChannel(contact);
    if ('error' in built) {
      setInlineError(built.error);
      return;
    }

    try {
      submittedRef.current = true;
      const result = await sendInvite.mutate(built);
      await Haptics.notificationAsync(
        Haptics.NotificationFeedbackType.Success,
      );
      onAfterSubmit();
      const masked = result.invite.contactMasked ?? 'your friend';
      toast.show({
        message: result.duplicate
          ? `Already invited ${masked}`
          : `Invite sent to ${masked}`,
        variant: result.duplicate ? 'info' : 'success',
      });
      handleClose();
    } catch (e) {
      const message =
        e instanceof ApiError
          ? mapErrorCode(e.code) ?? e.message
          : 'Could not send the invite. Please try again.';
      setInlineError(message);
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={handleClose}
    >
      <SafeAreaView
        edges={['left', 'right', 'bottom']}
        style={[styles.safe, { backgroundColor: colors.background }]}
      >
        <View
          style={[
            styles.header,
            {
              backgroundColor: colors.surface,
              borderBottomColor: colors.border,
              paddingTop: insets.top + 14,
            },
          ]}
        >
          <TouchableOpacity onPress={handleClose} style={styles.backBtn}>
            <Text style={[styles.modalCancel, { color: colors.primary }]}>
              Cancel
            </Text>
          </TouchableOpacity>
          <Text style={[styles.title, { color: colors.text }]}>
            Send invite
          </Text>
          <View style={{ width: 60 }} />
        </View>
        <ScrollView
          contentContainerStyle={[styles.scroll, { paddingBottom: 24 }]}
          keyboardShouldPersistTaps="handled"
        >
          <Text
            style={[
              styles.modalLabel,
              { color: colors.textSecondary, marginTop: 12 },
            ]}
          >
            Friend's email or phone
          </Text>
          <TextInput
            style={[
              styles.input,
              {
                backgroundColor: colors.surface,
                borderColor: colors.border,
                color: colors.text,
              },
            ]}
            placeholder="bob@example.com or +447911123456"
            placeholderTextColor={colors.textTertiary}
            value={contact}
            onChangeText={setContact}
            autoCapitalize="none"
            autoCorrect={false}
            keyboardType="email-address"
            editable={!sendInvite.loading}
          />

          <Text style={[styles.modalLabel, { color: colors.textSecondary }]}>
            Their name (optional)
          </Text>
          <TextInput
            style={[
              styles.input,
              {
                backgroundColor: colors.surface,
                borderColor: colors.border,
                color: colors.text,
              },
            ]}
            placeholder="Bob"
            placeholderTextColor={colors.textTertiary}
            value={displayName}
            onChangeText={setDisplayName}
            autoCapitalize="words"
            editable={!sendInvite.loading}
          />

          {inlineError && (
            <Text style={[styles.inlineError, { color: colors.red }]}>
              {inlineError}
            </Text>
          )}

          <TouchableOpacity
            style={[
              styles.shareBtn,
              {
                backgroundColor: colors.primary,
                marginTop: 18,
                opacity: sendInvite.loading ? 0.7 : 1,
              },
            ]}
            onPress={onSubmit}
            disabled={sendInvite.loading}
            accessibilityRole="button"
          >
            {sendInvite.loading ? (
              <ActivityIndicator size="small" color="#fff" />
            ) : (
              <Text style={styles.shareBtnText}>Send invite</Text>
            )}
          </TouchableOpacity>

          <Text
            style={[
              styles.modalNote,
              { color: colors.textTertiary, marginTop: 12 },
            ]}
          >
            We'll send your friend a one-off message with your code. We never
            store the contact details.
          </Text>
        </ScrollView>
      </SafeAreaView>
    </Modal>
  );
}

// --- Styles ---------------------------------------------------------------

const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  backBtn: {
    minWidth: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 19, fontFamily: 'Inter-SemiBold' },
  scroll: { padding: 16 },
  hero: { alignItems: 'center', gap: 10, paddingVertical: 20 },
  heroIconBg: {
    width: 80,
    height: 80,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitle: {
    fontSize: 26,
    fontFamily: 'Inter-Bold',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  heroSub: {
    fontSize: 15,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
    lineHeight: 21,
    paddingHorizontal: 12,
  },
  codeCard: {
    borderRadius: 20,
    padding: 20,
    gap: 12,
    marginBottom: 16,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  codeLabel: { fontSize: 13, fontFamily: 'Inter-SemiBold', letterSpacing: 0.5 },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderStyle: 'dashed',
  },
  codeText: { fontSize: 26, fontFamily: 'Inter-Bold', letterSpacing: 3 },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    paddingVertical: 14,
  },
  shareBtnText: { fontSize: 16, fontFamily: 'Inter-SemiBold', color: '#fff' },
  inviteBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    paddingVertical: 12,
    borderWidth: 1.5,
  },
  inviteBtnText: { fontSize: 15, fontFamily: 'Inter-SemiBold' },
  statsRow: {
    flexDirection: 'row',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  statItem: { flex: 1, alignItems: 'center', gap: 4 },
  statValue: { fontSize: 22, fontFamily: 'Inter-Bold' },
  statLabel: { fontSize: 13, fontFamily: 'Inter-Regular' },
  capRow: {
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    gap: 8,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  capText: { fontSize: 14, fontFamily: 'Inter-Regular' },
  capTrack: { height: 6, borderRadius: 3, overflow: 'hidden' },
  capFill: { height: 6, borderRadius: 3 },
  capWarn: { fontSize: 13, fontFamily: 'Inter-SemiBold' },
  termsCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    gap: 14,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 17, fontFamily: 'Inter-Bold', marginBottom: 10 },
  groupHeader: {
    fontSize: 13,
    fontFamily: 'Inter-SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  friendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendAvatarText: { fontSize: 16, fontFamily: 'Inter-Bold' },
  friendInfo: { flex: 1 },
  friendName: { fontSize: 15, fontFamily: 'Inter-SemiBold' },
  friendReward: { fontSize: 13, fontFamily: 'Inter-SemiBold', marginTop: 2 },
  stageChip: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  stageChipText: { fontSize: 12, fontFamily: 'Inter-SemiBold' },
  step: { flexDirection: 'row', gap: 14 },
  stepNum: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  stepNumText: { fontSize: 13, fontFamily: 'Inter-Bold', color: '#fff' },
  stepContent: { flex: 1, gap: 2 },
  stepTitle: { fontSize: 15, fontFamily: 'Inter-SemiBold' },
  stepDesc: { fontSize: 14, fontFamily: 'Inter-Regular', lineHeight: 19 },
  emptyCard: {
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyTitle: { fontSize: 16, fontFamily: 'Inter-SemiBold' },
  emptySub: { fontSize: 14, fontFamily: 'Inter-Regular', textAlign: 'center' },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    gap: 12,
  },
  placeholderTitle: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    textAlign: 'center',
  },
  placeholderSub: {
    fontSize: 15,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
    lineHeight: 21,
  },
  modalCancel: { fontSize: 16, fontFamily: 'Inter-SemiBold' },
  modalLabel: {
    fontSize: 13,
    fontFamily: 'Inter-SemiBold',
    marginTop: 14,
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: 'Inter-Regular',
  },
  inlineError: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    marginTop: 10,
  },
  modalNote: { fontSize: 12, fontFamily: 'Inter-Regular', lineHeight: 16 },
});
