// useCreatePaymentMethod — POST /payment-methods.
//
// Called by the add-flow state machine after WebBrowser returns with an
// opaque PSP token. Idempotent (key is generated by useMutation, rotated
// on success). On success: dispatch UPSERT_API and invalidate the list
// cache so the next focus refetch reads fresh data.

import { useWallet } from '@/context/WalletContext';
import type {
  CreatePaymentMethodRequest,
  PaymentMethodEnvelopeResponse,
} from '@/types/paymentMethods';
import { paymentMethodsApi } from '@/utils/api/paymentMethods';
import { useMutation, type MutationResult } from './useMutation';
import { PAYMENT_METHODS_QUERY_KEY } from './usePaymentMethods';

export interface UseCreatePaymentMethodOptions {
  onSuccess?: (response: PaymentMethodEnvelopeResponse) => void;
  onError?: (error: Error) => void;
}

export function useCreatePaymentMethod(
  options: UseCreatePaymentMethodOptions = {},
): MutationResult<CreatePaymentMethodRequest, PaymentMethodEnvelopeResponse> {
  const { dispatch } = useWallet();

  return useMutation<CreatePaymentMethodRequest, PaymentMethodEnvelopeResponse>(
    (vars, { idempotencyKey }) => paymentMethodsApi.create(vars, idempotencyKey),
    {
      retry: 1,
      invalidateKeys: [PAYMENT_METHODS_QUERY_KEY],
      onSuccess: (response) => {
        dispatch({
          type: 'PAYMENT_METHODS/UPSERT',
          payload: response.paymentMethod,
        });
        options.onSuccess?.(response);
      },
      onError: (error) => options.onError?.(error),
    },
  );
}
