// useRequestCardIssuance — POST /card/request-issuance.
//
// Idempotency-Key generated by useMutation (rotated on success). Backend
// rate limit: 5 req/hour per customer — never auto-retry on 4xx/429.

import { useWallet } from '@/context/WalletContext';
import type { Card, RequestIssuanceRequest } from '@/types/card';
import { cardApi } from '@/utils/api/card';
import { CARD_QUERY_KEY } from './useCard';
import { useMutation, type MutationResult } from './useMutation';

interface CardEnvelope {
  card: Card | null;
}

export function useRequestCardIssuance(): MutationResult<
  RequestIssuanceRequest,
  CardEnvelope
> {
  const { dispatch } = useWallet();

  return useMutation<RequestIssuanceRequest, CardEnvelope>(
    (vars, { idempotencyKey }) => cardApi.requestIssuance(vars, idempotencyKey),
    {
      // 5/hour hard limit — don't retry on 429.
      retry: 0,
      invalidateKeys: [CARD_QUERY_KEY],
      onSuccess: (response) => {
        dispatch({ type: 'CARD/SET_API', payload: response.card });
      },
    },
  );
}
